package math

import (
	"math"
	"reflect"
)

var Float32bits = reflect.ValueOf(math.Float32bits)
var Float32frombits = reflect.ValueOf(math.Float32frombits)
var Float64bits = reflect.ValueOf(math.Float64bits)
var Float64frombits = reflect.ValueOf(math.Float64frombits)
var Erf = reflect.ValueOf(math.Erf)
var Erfc = reflect.ValueOf(math.Erfc)
var Log1p = reflect.ValueOf(math.Log1p)
var Hypot = reflect.ValueOf(math.Hypot)
var Nextafter32 = reflect.ValueOf(math.Nextafter32)
var Nextafter = reflect.ValueOf(math.Nextafter)
var Copysign = reflect.ValueOf(math.Copysign)
var Pow10 = reflect.ValueOf(math.Pow10)
var Acosh = reflect.ValueOf(math.Acosh)
var Exp = reflect.ValueOf(math.Exp)
var Exp2 = reflect.ValueOf(math.Exp2)
var Sin = reflect.ValueOf(math.Sin)
var Cos = reflect.ValueOf(math.Cos)
var Abs = reflect.ValueOf(math.Abs)
var Ceil = reflect.ValueOf(math.Ceil)
var Trunc = reflect.ValueOf(math.Trunc)
var Floor = reflect.ValueOf(math.Floor)
var Cbrt = reflect.ValueOf(math.Cbrt)
var J1 = reflect.ValueOf(math.J1)
var Y1 = reflect.ValueOf(math.Y1)
var Tanh = reflect.ValueOf(math.Tanh)
var Asinh = reflect.ValueOf(math.Asinh)
var Pow = reflect.ValueOf(math.Pow)
var Atan = reflect.ValueOf(math.Atan)
var Sincos = reflect.ValueOf(math.Sincos)
var IsInf = reflect.ValueOf(math.IsInf)
var Inf = reflect.ValueOf(math.Inf)
var NaN = reflect.ValueOf(math.NaN)
var IsNaN = reflect.ValueOf(math.IsNaN)
var Mod = reflect.ValueOf(math.Mod)
var Tan = reflect.ValueOf(math.Tan)
var Gamma = reflect.ValueOf(math.Gamma)
var Y0 = reflect.ValueOf(math.Y0)
var J0 = reflect.ValueOf(math.J0)
var Asin = reflect.ValueOf(math.Asin)
var Acos = reflect.ValueOf(math.Acos)
var Sincos = reflect.ValueOf(math.Sincos)
var Log10 = reflect.ValueOf(math.Log10)
var Log2 = reflect.ValueOf(math.Log2)
var Cosh = reflect.ValueOf(math.Cosh)
var Sinh = reflect.ValueOf(math.Sinh)
var Logb = reflect.ValueOf(math.Logb)
var Ilogb = reflect.ValueOf(math.Ilogb)
var Lgamma = reflect.ValueOf(math.Lgamma)
var Sqrt = reflect.ValueOf(math.Sqrt)
var Dim = reflect.ValueOf(math.Dim)
var Max = reflect.ValueOf(math.Max)
var Min = reflect.ValueOf(math.Min)
var Log = reflect.ValueOf(math.Log)
var Yn = reflect.ValueOf(math.Yn)
var Jn = reflect.ValueOf(math.Jn)
var Frexp = reflect.ValueOf(math.Frexp)
var Expm1 = reflect.ValueOf(math.Expm1)
var Ldexp = reflect.ValueOf(math.Ldexp)
var Atanh = reflect.ValueOf(math.Atanh)
var Atan2 = reflect.ValueOf(math.Atan2)
var Modf = reflect.ValueOf(math.Modf)
var Signbit = reflect.ValueOf(math.Signbit)
var Remainder = reflect.ValueOf(math.Remainder)
